protected/controllers/ProjectController.php
<?php

class ProjectController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Project;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Project']))
		{
			$model->attributes=$_POST['Project'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Project']))
		{
			$model->attributes=$_POST['Project'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Project');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Project('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Project']))
			$model->attributes=$_GET['Project'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Project the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Project::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Project $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='project-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/controllers/RoomController.php
<?php

class RoomController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Room;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Room']))
		{
			$model->attributes=$_POST['Room'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Room']))
		{
			$model->attributes=$_POST['Room'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Room');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Room('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Room']))
			$model->attributes=$_GET['Room'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Room the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Room::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Room $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='room-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/controllers/UserController.php
<?php

class UserController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('create'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('view','update','modify','off'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete','index','view'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView()
	{
		$this->render('view',array(
			'model'=>$this->loadModel(Yii::app()->user->id),
		));
	}

	public function actionModify()
	{
		$model=$this->loadModel(Yii::app()->user->id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('modify',array(
			'model'=>$model,
		));
	}
	
	public function actionOff()
	{
		$model=$this->loadModel(Yii::app()->user->id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			if($model->save())
				$this->redirect(array('/dailyreport/index','id'=>$model->id));
		}

		$this->render('off',array(
			'model'=>$model,
		));
	}
	
	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new User;

		// Uncomment the following line if AJAX validation is needed
		$this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate()
	{
		$model=$this->loadModel(Yii::app()->user->id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('User');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new User('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['User']))
			$model->attributes=$_GET['User'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return User the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=User::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param User $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='user-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/dailyreport/_form.php
<?php
/* @var $this DailyreportController */
/* @var $model Dailyreport */
/* @var $form CActiveForm */
?>

<script type="text/javascript">
		function read(){
			var maxl=50;
			var content=document.getElementById("con").value;
			var relcon=content.split(/[\t*\s*]/g);
			var s=relcon.join("").length;
			//var s=Array.join(content.split(/[\t*\s*]/g),"").length;
			//var s=document.getElementById("con").value.length;
			if(maxl>s)
				document.getElementById("num").innerHTML="已输入"+s+"/"+maxl+" 字符，还需要至少"+(maxl-s)+"个字。（注意：空格、回车不算字数。）";
			else
				document.getElementById("num").innerHTML="已输入"+s+"个字符，已满足要求！";
		}
</script>
<body onload="read()">
<div class="form">
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'dailyreport-form',
	'enableAjaxValidation'=>false,
	'enableClientValidation'=>false,
)); ?>
	
	<div class="row">
		<?php echo $form->textArea($model,'content',array('rows'=>8,'cols'=>20,'id'=>'con','style'=>"height:150px;width:450px;",'onkeyup'=>'read()')); ?>
		<div><span id="num" style="color:purple">已输入0个字符</span></div>
		<?php echo $form->error($model,'content'); ?>
	</div>
	<?php if(Yii::app()->user->hasFlash('warning')):?>
	<div id="flash-warning">
			<?php $this->widget('bootstrap.widgets.TbAlert', array(
				'block'=>true, // display a larger alert block?
				'fade'=>true, // use transitions?
				'closeText'=>'&times;', // close link text - if set to false, no close link is displayed
				'alerts'=>array( // configurations per alert type
					'warning'=>array('block'=>true, 'fade'=>true, 'closeText'=>'&times;'), // success, info, warning, error or danger
				),
		)); ?>
	</div>
	<?php endif;?>
	<div class="row buttons" style="text-align:center">
	<?php $this->widget('bootstrap.widgets.TbButton',array(
		'buttonType'=>'submit',
		'type'=>$model->isNewRecord? 'success':'info',
		'size'=>'large',
		'icon'=>'icon-ok',
		'label'=>$model->isNewRecord? '发布':'保存',
	));?>
	</div>
<?php $this->endWidget(); ?>
</div>
</body>

protected/views/dailyreport/_search.php
<?php
/* @var $this DailyreportController */
/* @var $model Dailyreport */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'content'); ?>
		<?php echo $form->textArea($model,'content',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'create_time'); ?>
		<?php echo $form->textField($model,'create_time'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'author_id'); ?>
		<?php echo $form->textField($model,'author_id'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/dailyreport/_view.php
<?php
/* @var $this DailyreportController */
/* @var $data Dailyreport */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('content')); ?>:</b>
	<?php echo CHtml::encode($data->content); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('create_time')); ?>:</b>
	<?php echo CHtml::encode($data->create_time); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('author_id')); ?>:</b>
	<?php echo CHtml::encode($data->author_id); ?>
	<br />


</div>

protected/views/dailyreport/admin.php
<?php
/* @var $this DailyreportController */
/* @var $model Dailyreport */

$this->breadcrumbs=array(
	'日报'=>array('index'),
	'管理',
);

$this->menu=array(
	array('label'=>'日报列表', 'url'=>array('index')),
	array('label'=>'写日报', 'url'=>array('create')),
);
?>

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'dailyreport-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		array(
			'name'=>'author',
			'value'=>'User::item($data["author_id"])',
			'filter'=>User::items(),
		),
		'content',
		'create_time',
		//'id',
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

protected/views/dailyreport/create.php
<?php
/* @var $this DailyreportController */
/* @var $model Dailyreport */

$this->widget('bootstrap.widgets.TbBreadcrumbs',array(
	'links'=>array('日报'=>array('index'),'写日报'),
	'homeLink'=>false,
));?>

<h1>写日报</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/dailyreport/error.php
<?php
/* @var $this DailyreportController */
/* @var $model Dailyreport */

$this->widget('bootstrap.widgets.TbBreadcrumbs',array(
	'links'=>array('日报'=>'index','今天我的日报'),
	'homeLink'=>false,
));?>

<h2>亲,您的日报还没发呢</h2>

protected/views/dailyreport/index.php
<div class="span10">
<?php if(!Yii::app()->user->isGuest)
$this->widget('bootstrap.widgets.TbMenu',array(
	'type'=>'tabs',
	'items'=>array(
	array('label'=>'写日报','icon'=>'pencil','url'=>array('create')),
	array('label'=>'今天日报','icon'=>'eye-open','url'=>array('view')),
	array('label'=>'更改日报','icon'=>'edit','url'=>array('update')),
	array('label'=>'日报记录','icon'=>'list-alt','url'=>array('show')),
	array('label'=>'请假了','icon'=>'icon-plane','url'=>array('/user/off')),
	array('label'=>'日报设置','icon'=>'cog','url'=>array('/user/modify')),
	array('label'=>'添加项目','url'=>array('/project/create'),'visible'=>Yii::app()->user->name==='admin'),
	array('label'=>'添加房间','url'=>array('/room/create'),'visible'=>Yii::app()->user->name==='admin'),
	array('label'=>'开启定时任务','url'=>array('open'),'visible'=>Yii::app()->user->name==='admin'),
	array('label'=>'邮件提醒','url'=>array('remind'),'visible'=>Yii::app()->user->name==='admin'),
	array('label'=>'管理日报', 'url'=>array('admin'),'visible'=>Yii::app()->user->name==='admin'),
	),
));
?>

<?php $this->widget('bootstrap.widgets.TbGridView', array(
	'id'=>'dailyreport-grid',
	'type'=>'bordered',
	'dataProvider'=>$model->search(),
	//'filter'=>$model,
	'columns'=>array(
		array(
			'name'=>'作者',
			'value'=>'User::item($data["author_id"])',
			'filter'=>User::items(),
			'htmlOptions'=>array('style'=>'width:55px;text-align:center'),
		),
		array(
			'name'=>'日报内容',
			'value'=>'$data["content"]',
			'filter'=>false,
			'htmlOptions'=>array('style'=>'width:500px'),
		),
		//'content',
		//'create_time',
		array(
			'name'=>'项目组',
			'value'=>'Project::item($data["author_id"])',
			'filter'=>false,
			'htmlOptions'=>array('style'=>'width:160px;text-align:center'),
		),
		array(
			'name'=>'教研室',
			'value'=>'Room::item($data["author_id"])',
			'filter'=>false,
			'htmlOptions'=>array('style'=>'width:50px;text-align:center'),
		),
		array(
			'name'=>'发布时间',
			// 'value'=>'Yii::app()->format->formatDateTime($data["create_time"])',
			'value'=>'$data["create_time"]',
			'filter'=>false,
			'htmlOptions'=>array('style'=>'width:130px;text-align:center'),
		),
	),
)); ?>
</div>

<meta charset='utf-8'>

protected/views/dailyreport/open.php
<div class="span-19">
	<div id="content">
		<?php echo '开启定时服务'; ?>
	</div><!-- content -->
</div>
<?php
	DailyreportController::sendEmails();
?>

protected/views/dailyreport/remind.php
<div class="span-19">
	<div id="content">
		<?php echo '邮件提醒'; ?>
	</div><!-- content -->
</div>
<?php
	DailyreportController::sendCountEmails();
?>

protected/views/dailyreport/service.php
<meta charset='utf-8'>
<?php
DailyreportController::sendEmails();
?>

protected/views/dailyreport/show.php
<?php
/* @var $this DailyreportController */
/* @var $dataProvider CActiveDataProvider */

$this->widget('bootstrap.widgets.TbBreadCrumbs',array(
	'links'=>array('日报'=>array('index'),'自己日报记录'),
	'homeLink'=>false,
));
?>

<?php $this->widget('bootstrap.widgets.TbGridView', array(
	'id'=>'dailyreport-grid',
	'dataProvider'=>$model->searchMyinfo(),
	//'dataProvider'=>Yii::app()->user->dailyreports,
	//'filter'=>$model,
	'columns'=>array(
		// array(
			// 'name'=>'作者',
			// 'value'=>'User::item($data["author_id"])',
			// 'filter'=>false,
		// ),
		array(
		'name'=>'日报内容',
		'value'=>'$data["content"]',
		'filter'=>false,
		),
		array(
		'name'=>'时间',
		'value'=>'$data["create_time"]',
		'filter'=>false,
		),
	),
)); ?>

protected/views/dailyreport/test.php
<?php
/* @var $this DailyreportController */
/* @var $model Dailyreport */
/* @var $form CActiveForm */
?>

<div class="form">
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'dailyreport-form',
	'enableAjaxValidation'=>true,
	'enableClientValidation'=>true,
)); ?>
	
	<div class="row">
		<?php echo $form->textArea($model,'content',array('rows'=>8,'cols'=>20,'onkeyup'=>'read()','style'=>"height:150px;width:450px;")); ?>
		<div><span id="num" style="color:purple">已输入0个字符</span></div>
		<?php echo $form->error($model,'content'); ?>
	</div>
	<div class="row buttons" style="text-align:center">
	<?php $this->widget('bootstrap.widgets.TbButton',array(
		'buttonType'=>'submit',
		'type'=>$model->isNewRecord? 'success':'info',
		'size'=>'large',
		'icon'=>'icon-ok',
		'label'=>$model->isNewRecord? '发布':'保存',
	));?>
	</div>
<?php $this->endWidget(); ?>

</div>

protected/views/dailyreport/update.php
<?php
/* @var $this DailyreportController */
/* @var $model Dailyreport */

$this->widget('bootstrap.widgets.TbBreadcrumbs',array(
	'links'=>array('日报'=>array('index'),'更改今天日报'),
	'homeLink'=>false,
));
?>

<h2>更该今天的日报</h2>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/dailyreport/view.php
<?php
/* @var $this DailyreportController */
/* @var $model Dailyreport */

$this->widget('bootstrap.widgets.TbBreadcrumbs',array(
	'links'=>array('日报'=>array('index'),'今天我的日报'),
	'homeLink'=>false,
));?>

<h2>今天日报</h2>

<?php $this->widget('bootstrap.widgets.TbDetailView', array(
	'data'=>$model,
	'type'=>'bordered',
	'attributes'=>array(
		array(
			'name'=>'content',
			'label'=>'内容',
			'value'=>$model->content,
		),
		array(
			'name'=>'create_time',
			'label'=>'发布时间',	
			'value'=>$model->create_time,
		),
		array(
			'label'=>'作者',
			'value'=>Yii::app()->user->name,
		),
	),
)); ?>